"""Initial schema

Revision ID: 0b7179d81ccc
Revises: 
Create Date: 2026-08-21 22:52:39.555936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7179d81ccc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agent_rules_merchant_id'), 'agent_rules', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_recovery_case_id'), 'audit_logs', ['recovery_case_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_recovery_actions_action_type'), 'recovery_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_recovery_actions_recovery_case_id'), 'recovery_actions', ['recovery_case_id'], unique=False)
    op.alter_column('recovery_cases', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=4, scale=3),
               existing_nullable=True)
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_transaction_id'), 'recovery_cases', ['transaction_id'], unique=False)
    op.create_check_constraint('valid_case_status', 'recovery_cases', "status IN ('open', 'recovered', 'failed', 'pending_human_review')")
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_check_constraint('valid_tx_status', 'transactions', "status IN ('success', 'failed', 'abandoned')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('valid_tx_status', 'transactions', type_='check')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_constraint('valid_case_status', 'recovery_cases', type_='check')
    op.drop_index(op.f('ix_recovery_cases_transaction_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.alter_column('recovery_cases', 'confidence_score',
               existing_type=sa.Numeric(precision=4, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index(op.f('ix_recovery_actions_recovery_case_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_action_type'), table_name='recovery_actions')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_recovery_case_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_agent_rules_merchant_id'), table_name='agent_rules')
    # ### end Alembic commands ###
