"""Add SystemException model

Revision ID: 323b0e264f8b
Revises: 6cbffeb727e8
Create Date: 2026-08-25 00:09:53.323417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323b0e264f8b'
down_revision: Union[str, Sequence[str], None] = '6cbffeb727e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exceptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('recovery_case_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_merchant_id'), 'exceptions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_exceptions_recovery_case_id'), 'exceptions', ['recovery_case_id'], unique=False)
    op.create_index(op.f('ix_exceptions_severity'), 'exceptions', ['severity'], unique=False)
    op.create_index(op.f('ix_exceptions_status'), 'exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_exceptions_transaction_id'), 'exceptions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_exceptions_type'), 'exceptions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptions_type'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_transaction_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_status'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_severity'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_recovery_case_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_merchant_id'), table_name='exceptions')
    op.drop_table('exceptions')
    # ### end Alembic commands ###
