"""audit_system

Revision ID: 6cbffeb727e8
Revises: c0da953e1bbf
Create Date: 2026-08-22 14:50:24.347051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbffeb727e8'
down_revision: Union[str, Sequence[str], None] = 'c0da953e1bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('transaction_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('event', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('actor', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_audit_logs_transaction_id'), 'audit_logs', ['transaction_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'transactions', ['transaction_id'], ['id'])
    op.drop_column('audit_logs', 'action')
    op.drop_column('audit_logs', 'reason')
    op.drop_column('audit_logs', 'entity_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_transaction_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'actor')
    op.drop_column('audit_logs', 'event')
    op.drop_column('audit_logs', 'transaction_id')
    # ### end Alembic commands ###
