"""enterprise_upgrade

Revision ID: 941460017019
Revises: f9ef4d0fb711
Create Date: 2026-09-03 09:48:06.980984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '941460017019'
down_revision: Union[str, Sequence[str], None] = 'f9ef4d0fb711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptions_merchant_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_recovery_case_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_severity'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_status'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_transaction_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_type'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_agent_rules_merchant_id'), table_name='agent_rules')
    op.drop_table('agent_rules')
    op.add_column('recovery_cases', sa.Column('risk_severity', sa.String(), nullable=True))
    op.add_column('recovery_cases', sa.Column('ai_trace_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'ai_trace_id')
    op.drop_column('recovery_cases', 'risk_severity')
    op.create_table('agent_rules',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('merchant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rule_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rule_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('agent_rules_merchant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_rules_pkey'))
    )
    op.create_index(op.f('ix_agent_rules_merchant_id'), 'agent_rules', ['merchant_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('merchant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recovery_case_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('exceptions_merchant_id_fkey')),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('exceptions_recovery_case_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('exceptions_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exceptions_pkey'))
    )
    op.create_index(op.f('ix_exceptions_type'), 'exceptions', ['type'], unique=False)
    op.create_index(op.f('ix_exceptions_transaction_id'), 'exceptions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_exceptions_status'), 'exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_exceptions_severity'), 'exceptions', ['severity'], unique=False)
    op.create_index(op.f('ix_exceptions_recovery_case_id'), 'exceptions', ['recovery_case_id'], unique=False)
    op.create_index(op.f('ix_exceptions_merchant_id'), 'exceptions', ['merchant_id'], unique=False)
    # ### end Alembic commands ###
