"""Add risk fields to RecoveryCase

Revision ID: c0da953e1bbf
Revises: 0b7179d81ccc
Create Date: 2026-08-22 11:31:00.470832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0da953e1bbf'
down_revision: Union[str, Sequence[str], None] = '0b7179d81ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('risk_type', sa.String(), nullable=True))
    op.add_column('recovery_cases', sa.Column('risk_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('recovery_cases', sa.Column('signals', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'signals')
    op.drop_column('recovery_cases', 'risk_amount')
    op.drop_column('recovery_cases', 'risk_type')
    # ### end Alembic commands ###
