"""Add webhook idempotency models

Revision ID: f9ef4d0fb711
Revises: 323b0e264f8b
Create Date: 2026-08-29 11:20:50.395475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ef4d0fb711'
down_revision: Union[str, Sequence[str], None] = '323b0e264f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('webhook_event_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('event_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'event_timestamp')
    op.drop_column('transactions', 'webhook_event_type')
    # ### end Alembic commands ###
